[workspace]
members = ["cli"]

[package]
name = "silpkg"
version = "0.1.0"
edition = "2021"
authors = ["Fishhh"]
license = "MIT OR Apache-2.0"
description = "A library for working with SIL PKG archives"

[dependencies]
# TODO: Make deflate support optional
flate2 = { version = "1.0" } #, features = ["zlib-ng"], default-features = false }
bitflags = "1"
log = "0.4"
thiserror = "1"

macros = { path = "./macros" }

[dev-dependencies]
# Enable logging during testing
test-log = "0.2.11"
env_logger = "0.10"
# Generate random test data
rand = "0.8"
