[package]
name = "macros"
license = "MIT OR Apache-2.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full", "visit-mut", "parsing"] }
quote = "1.0"
proc-macro2 = "1.0"
